import Head from "next/head";
import HomeComponent from "@/components/Home";

export default function Home() {
  return (
    <>
      <Head>
        <title>RJ File Manager</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-4xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Welcome To{" "}
            <span className="text-[hsl(280,100%,70%)]">RJ File Manager</span>
          </h1>
          <HomeComponent />
        </div>
      </main>
    </>
  );
}
